import {useMutation, UseMutationOptions, useQueryClient} from "@tanstack/react-query";
import {
  assignPlanToStudentMutation,
  bulkUpdateCommitmentsMutation,
  createStudentMutation,
  deleteStudentMutation, findStudentByIdOptions,
  restoreStudentMutation,
  updateStudentMutation
} from "@/lib/api-client/@tanstack/react-query.gen";
import {apiClient} from "@/lib/client";
import type {
  AssignPlanToStudentData,
  AssignPlanToStudentResponse,
  BulkUpdateCommitmentsData,
  BulkUpdateCommitmentsResponse,
  Options,
  StudentResponseDto,
  UpdateStudentData,
} from "@/lib/api-client";

/**
 * Hooks that wrap generated mutation factories and add onSuccess invalidations
 * for the students list (findAll).
 *
 * These avoid editing autogenerated files and centralize invalidation logic.
 */

export const useCreateStudent = () => {
  const queryClient = useQueryClient();
  const base = createStudentMutation({ client: apiClient });
  const baseOnSuccess = base.onSuccess;

  return useMutation({
    ...base,
    onSuccess: async (...args) => {
      try {
        if (baseOnSuccess) {
          try {
            await baseOnSuccess(...args);
          } catch {
            // Best-effort: preserve base behaviour even if hook consumer swallows errors
          }
        }
      } catch {
        // ignore
      }

      await queryClient.invalidateQueries({
        predicate: (q) => Array.isArray(q.queryKey) && q.queryKey[0]?._id === "findAllStudents",
      });
    },
  });
};

export const useUpdateStudent = (options: UseMutationOptions<StudentResponseDto, Error, Options<UpdateStudentData>>) => {
  const queryClient = useQueryClient();
  const base = updateStudentMutation({ client: apiClient });
  const baseOnSuccess = base.onSuccess;

  return useMutation({
    ...base,
    ...options,
    onSuccess: async (data, variables, ...args) => {
      if (baseOnSuccess) {
        try {
          await baseOnSuccess(data, variables, ...args);
        } catch {
          // ignore
        }
      }

      if (options.onSuccess) {
        try {
          await options.onSuccess(data, variables, ...args);
        } catch {
          // ignore
        }
      }
      // Invalidate the students list
      await Promise.all([queryClient.invalidateQueries({
        predicate: (q) => Array.isArray(q.queryKey) && q.queryKey[0]?._id === 'findAllStudents'
      }),
        // Invalidate the specific cached student (findById) so the details refresh
        queryClient.invalidateQueries({
          queryKey: findStudentByIdOptions({path: {id: variables.path.id ?? ""}, client: apiClient}).queryKey
        })])
    }
  });
};

export const useDeleteStudent = () => {
  const queryClient = useQueryClient();
  const base = deleteStudentMutation({ client: apiClient });
  const baseOnSuccess = base.onSuccess;

  return useMutation({
    ...base,
    onSuccess: async (...args) => {
      if (baseOnSuccess) {
        try {
          await baseOnSuccess(...args);
        } catch {
          // ignore
        }
      }
      await queryClient.invalidateQueries({
        predicate: (q) => Array.isArray(q.queryKey) && q.queryKey[0]?._id === "findAllStudents",
      });
    },
  });
};

export const useRestoreStudent = () => {
  const queryClient = useQueryClient();
  const base = restoreStudentMutation({ client: apiClient });
  const baseOnSuccess = base.onSuccess;

  return useMutation({
    ...base,
    onSuccess: async (...args) => {
      if (baseOnSuccess) {
        try {
          await baseOnSuccess(...args);
        } catch {
          // ignore
        }
      }
      await queryClient.invalidateQueries({
        predicate: (q) => Array.isArray(q.queryKey) && q.queryKey[0]?._id === "findAllStudents",
      });
    },
  });
};

export const assignPlanToStudentMutationOptions = () =>
  assignPlanToStudentMutation({ client: apiClient });

export type AssignPlanToStudentMutationVariables = Options<AssignPlanToStudentData>;
export type AssignPlanToStudentMutationResponse = AssignPlanToStudentResponse;

export type AssignPlanToStudentMutationOptions = ReturnType<typeof assignPlanToStudentMutationOptions>;

export const bulkUpdateCommitmentsMutationOptions = () =>
  bulkUpdateCommitmentsMutation({ client: apiClient });

export type BulkUpdateCommitmentsMutationVariables = Options<BulkUpdateCommitmentsData>;
export type BulkUpdateCommitmentsMutationResponse = BulkUpdateCommitmentsResponse;

export type BulkUpdateCommitmentsMutationOptions = ReturnType<typeof bulkUpdateCommitmentsMutationOptions>;
