CREATE TABLE IF NOT EXISTS EVENTS (
   EVENT_ID UUID PRIMARY KEY,
   NAME VARCHAR(200) NOT NULL,
   EVENT_DATE DATE NOT NULL,
   START_TIME TIME,
   END_TIME TIME,
   LOCATION VARCHAR(255),
   DESCRIPTION TEXT,
   INSTRUCTOR VARCHAR(120),
   PARTICIPANTS TEXT[],
   CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
   UPDATED_AT TIMESTAMP,
   DELETED_AT TIMESTAMP
);
