// This file is auto-generated by @hey-api/openapi-ts

export type CreateTrainerDto = {
    name?: string;
    email?: string;
    phone?: string;
    password?: string;
    address?: string;
    birthDate?: string;
    specialties?: Array<string>;
    compensationType?: 'HOURLY' | 'MONTHLY';
};

export type TrainerResponseDto = {
    id?: string;
    name?: string;
    email?: string;
    phone?: string;
    address?: string;
    birthDate?: string;
    specialties?: Array<string>;
    compensationType?: 'HOURLY' | 'MONTHLY';
    joinDate?: string;
    hoursWorked?: number;
};

export type AnamnesisRequestDto = {
    medication?: string;
    isDoctorAwareOfPhysicalActivity?: boolean;
    favoritePhysicalActivity?: string;
    hasInsomnia?: 'YES' | 'NO' | 'SOMETIMES';
    dietOrientedBy?: string;
    cardiacProblems?: string;
    hasHypertension?: boolean;
    chronicDiseases?: string;
    difficultiesInPhysicalActivities?: string;
    medicalOrientationsToAvoidPhysicalActivity?: string;
    surgeriesInTheLast12Months?: string;
    respiratoryProblems?: string;
    jointMuscularBackPain?: string;
    spinalDiscProblems?: string;
    diabetes?: string;
    smokingDuration?: string;
    alteredCholesterol?: boolean;
    osteoporosisLocation?: string;
};

export type PhysicalImpairmentRequestDto = {
    type: 'VISUAL' | 'AUDITORY' | 'MOTOR' | 'INTELLECTUAL' | 'OTHER';
    name: string;
    observations?: string;
};

export type StudentRequestDto = {
    email: string;
    name: string;
    surname: string;
    gender: 'M' | 'F' | 'O';
    birthDate: string;
    phone?: string;
    profession?: string;
    street?: string;
    number?: string;
    complement?: string;
    neighborhood?: string;
    cep?: string;
    emergencyContactName?: string;
    emergencyContactPhone?: string;
    emergencyContactRelationship?: string;
    objectives?: string;
    observations?: string;
    anamnesis?: AnamnesisRequestDto;
    physicalImpairments?: Array<PhysicalImpairmentRequestDto>;
};

export type AnamnesisResponseDto = {
    medication?: string;
    isDoctorAwareOfPhysicalActivity?: boolean;
    favoritePhysicalActivity?: string;
    hasInsomnia?: 'YES' | 'NO' | 'SOMETIMES';
    dietOrientedBy?: string;
    cardiacProblems?: string;
    hasHypertension?: boolean;
    chronicDiseases?: string;
    difficultiesInPhysicalActivities?: string;
    medicalOrientationsToAvoidPhysicalActivity?: string;
    surgeriesInTheLast12Months?: string;
    respiratoryProblems?: string;
    jointMuscularBackPain?: string;
    spinalDiscProblems?: string;
    diabetes?: string;
    smokingDuration?: string;
    alteredCholesterol?: boolean;
    osteoporosisLocation?: string;
};

export type PhysicalImpairmentResponseDto = {
    id?: string;
    type?: 'VISUAL' | 'AUDITORY' | 'MOTOR' | 'INTELLECTUAL' | 'OTHER';
    name?: string;
    observations?: string;
};

export type StudentResponseDto = {
    id?: string;
    email?: string;
    name?: string;
    surname?: string;
    gender?: 'M' | 'F' | 'O';
    birthDate?: string;
    phone?: string;
    profession?: string;
    street?: string;
    number?: string;
    complement?: string;
    neighborhood?: string;
    cep?: string;
    emergencyContactName?: string;
    emergencyContactPhone?: string;
    emergencyContactRelationship?: string;
    objectives?: string;
    observations?: string;
    registrationDate?: string;
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: string;
    anamnesis?: AnamnesisResponseDto;
    physicalImpairments?: Array<PhysicalImpairmentResponseDto>;
};

export type ExerciseRequestDto = {
    name: string;
    description?: string;
};

export type ExerciseResponseDto = {
    id?: string;
    name?: string;
    description?: string;
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: string;
};

export type AdministratorRequestDto = {
    firstName: string;
    lastName: string;
    email: string;
    password: string;
};

export type AdministratorResponseDto = {
    id?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    fullName?: string;
    createdAt?: string;
    updatedAt?: string;
    active?: boolean;
};

export type CreateUserRequestDto = {
    email: string;
    password: string;
    role?: 'ROLE_ADMIN' | 'ROLE_TRAINER';
};

export type UserResponseDto = {
    id?: string;
    email?: string;
    role?: 'ROLE_ADMIN' | 'ROLE_TRAINER';
};

export type ListTrainersDto = {
    id?: string;
    name?: string;
    email?: string;
    phone?: string;
    address?: string;
    birthDate?: string;
    specialties?: Array<string>;
    compensationType?: 'HOURLY' | 'MONTHLY';
    active?: boolean;
    joinDate?: string;
    hoursWorked?: number;
};

export type LoginRequestDto = {
    email: string;
    password: string;
};

export type JwtResponseDto = {
    id?: string;
    token?: string;
};

export type PatchUserRoleRequestDto = {
    role?: 'ROLE_ADMIN' | 'ROLE_TRAINER';
};

export type PatchExerciseRequestDto = {
    name?: string;
    description?: string;
};

export type PatchAdministratorRequestDto = {
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
};

export type Pageable = {
    page?: number;
    size?: number;
    sort?: Array<string>;
};

export type PageMetadata = {
    size?: number;
    number?: number;
    totalElements?: number;
    totalPages?: number;
};

export type PagedModelUserResponseDto = {
    content?: Array<UserResponseDto>;
    page?: PageMetadata;
};

export type PagedModelStudentResponseDto = {
    content?: Array<StudentResponseDto>;
    page?: PageMetadata;
};

export type PagedModelExerciseResponseDto = {
    content?: Array<ExerciseResponseDto>;
    page?: PageMetadata;
};

export type PagedModelAdministratorResponseDto = {
    content?: Array<AdministratorResponseDto>;
    page?: PageMetadata;
};

export type SoftDeleteTrainerUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/trainers/{id}';
};

export type SoftDeleteTrainerUserResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type FindTrainerByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/trainers/{id}';
};

export type FindTrainerByIdResponses = {
    /**
     * OK
     */
    200: ListTrainersDto;
};

export type FindTrainerByIdResponse = FindTrainerByIdResponses[keyof FindTrainerByIdResponses];

export type UpdateTrainerAndUserData = {
    body: CreateTrainerDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/trainers/{id}';
};

export type UpdateTrainerAndUserResponses = {
    /**
     * OK
     */
    200: TrainerResponseDto;
};

export type UpdateTrainerAndUserResponse = UpdateTrainerAndUserResponses[keyof UpdateTrainerAndUserResponses];

export type DeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/students/{id}';
};

export type DeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type FindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/students/{id}';
};

export type FindByIdResponses = {
    /**
     * OK
     */
    200: StudentResponseDto;
};

export type FindByIdResponse = FindByIdResponses[keyof FindByIdResponses];

export type UpdateData = {
    body: StudentRequestDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/students/{id}';
};

export type UpdateResponses = {
    /**
     * OK
     */
    200: StudentResponseDto;
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];

export type Delete1Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/exercises/{id}';
};

export type Delete1Responses = {
    /**
     * OK
     */
    200: unknown;
};

export type FindById1Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/exercises/{id}';
};

export type FindById1Responses = {
    /**
     * OK
     */
    200: ExerciseResponseDto;
};

export type FindById1Response = FindById1Responses[keyof FindById1Responses];

export type PatchData = {
    body: PatchExerciseRequestDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/exercises/{id}';
};

export type PatchResponses = {
    /**
     * OK
     */
    200: ExerciseResponseDto;
};

export type PatchResponse = PatchResponses[keyof PatchResponses];

export type Update1Data = {
    body: ExerciseRequestDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/exercises/{id}';
};

export type Update1Responses = {
    /**
     * OK
     */
    200: ExerciseResponseDto;
};

export type Update1Response = Update1Responses[keyof Update1Responses];

export type Delete2Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/administrators/{id}';
};

export type Delete2Responses = {
    /**
     * OK
     */
    200: unknown;
};

export type FindById2Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/administrators/{id}';
};

export type FindById2Responses = {
    /**
     * OK
     */
    200: AdministratorResponseDto;
};

export type FindById2Response = FindById2Responses[keyof FindById2Responses];

export type Patch1Data = {
    body: PatchAdministratorRequestDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/administrators/{id}';
};

export type Patch1Responses = {
    /**
     * OK
     */
    200: AdministratorResponseDto;
};

export type Patch1Response = Patch1Responses[keyof Patch1Responses];

export type Update2Data = {
    body: AdministratorRequestDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/administrators/{id}';
};

export type Update2Responses = {
    /**
     * OK
     */
    200: AdministratorResponseDto;
};

export type Update2Response = Update2Responses[keyof Update2Responses];

export type GetAllUsersSimpleData = {
    body?: never;
    path?: never;
    query: {
        pageable: Pageable;
    };
    url: '/users';
};

export type GetAllUsersSimpleResponses = {
    /**
     * OK
     */
    200: PagedModelUserResponseDto;
};

export type GetAllUsersSimpleResponse = GetAllUsersSimpleResponses[keyof GetAllUsersSimpleResponses];

export type CreateUserData = {
    body: CreateUserRequestDto;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUserResponses = {
    /**
     * OK
     */
    200: UserResponseDto;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type FindAllTrainersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/trainers';
};

export type FindAllTrainersResponses = {
    /**
     * OK
     */
    200: Array<ListTrainersDto>;
};

export type FindAllTrainersResponse = FindAllTrainersResponses[keyof FindAllTrainersResponses];

export type CreateTrainerAndUserData = {
    body: CreateTrainerDto;
    path?: never;
    query?: never;
    url: '/trainers';
};

export type CreateTrainerAndUserResponses = {
    /**
     * OK
     */
    200: ListTrainersDto;
};

export type CreateTrainerAndUserResponse = CreateTrainerAndUserResponses[keyof CreateTrainerAndUserResponses];

export type FindAllData = {
    body?: never;
    path?: never;
    query: {
        search?: string;
        gender?: string;
        profession?: string;
        minAge?: number;
        maxAge?: number;
        registrationPeriodMinDate?: string;
        registrationPeriodMaxDate?: string;
        includeInactive?: boolean;
        pageable: Pageable;
    };
    url: '/students';
};

export type FindAllResponses = {
    /**
     * OK
     */
    200: PagedModelStudentResponseDto;
};

export type FindAllResponse = FindAllResponses[keyof FindAllResponses];

export type CreateData = {
    body: StudentRequestDto;
    path?: never;
    query?: never;
    url: '/students';
};

export type CreateResponses = {
    /**
     * OK
     */
    200: StudentResponseDto;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type FindAll1Data = {
    body?: never;
    path?: never;
    query: {
        search?: string;
        includeInactive?: boolean;
        pageable: Pageable;
    };
    url: '/exercises';
};

export type FindAll1Responses = {
    /**
     * OK
     */
    200: PagedModelExerciseResponseDto;
};

export type FindAll1Response = FindAll1Responses[keyof FindAll1Responses];

export type Create1Data = {
    body: ExerciseRequestDto;
    path?: never;
    query?: never;
    url: '/exercises';
};

export type Create1Responses = {
    /**
     * OK
     */
    200: ExerciseResponseDto;
};

export type Create1Response = Create1Responses[keyof Create1Responses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    /**
     * OK
     */
    200: string;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LoginData = {
    body: LoginRequestDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: JwtResponseDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type FindAll2Data = {
    body?: never;
    path?: never;
    query: {
        search?: string;
        includeInactive?: boolean;
        pageable: Pageable;
    };
    url: '/administrators';
};

export type FindAll2Responses = {
    /**
     * OK
     */
    200: PagedModelAdministratorResponseDto;
};

export type FindAll2Response = FindAll2Responses[keyof FindAll2Responses];

export type Create2Data = {
    body: AdministratorRequestDto;
    path?: never;
    query?: never;
    url: '/administrators';
};

export type Create2Responses = {
    /**
     * OK
     */
    200: AdministratorResponseDto;
};

export type Create2Response = Create2Responses[keyof Create2Responses];

export type Patch2Data = {
    body: PatchUserRoleRequestDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type Patch2Responses = {
    /**
     * OK
     */
    200: UserResponseDto;
};

export type Patch2Response = Patch2Responses[keyof Patch2Responses];

export type RestoreData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/students/{id}/restore';
};

export type RestoreResponses = {
    /**
     * OK
     */
    200: StudentResponseDto;
};

export type RestoreResponse = RestoreResponses[keyof RestoreResponses];

export type Restore1Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/exercises/{id}/restore';
};

export type Restore1Responses = {
    /**
     * OK
     */
    200: ExerciseResponseDto;
};

export type Restore1Response = Restore1Responses[keyof Restore1Responses];

export type Restore2Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/administrators/{id}/restore';
};

export type Restore2Responses = {
    /**
     * OK
     */
    200: AdministratorResponseDto;
};

export type Restore2Response = Restore2Responses[keyof Restore2Responses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};